name: patchfusion
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
dependencies:
  - cuda=11.8
  - h5py=3.9.0 
  - hdf5=1.12.1
  - matplotlib=3.7.3 
  - matplotlib-base=3.7.3
  - numpy=1.24.4 
  # - opencv=4.6.0
  - pip=23.3.2 
  - python=3.8.18 
  - pytorch=2.1.2 
  - pytorch-cuda=11.8 
  - pytorch-mutex=1.0
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - json5=0.9.14
  - einops=0.7.0
  - scikit-image=0.20.0
  - pip:
    - huggingface-hub==0.20.1
    - timm==0.9.2
    - tqdm==4.66.1
    - wandb==0.16.1
    - opencv-python==4.8.1.78
    - imageio==2.33.1
    - mmengine==0.10.2
    - scipy==1.10.1
    - prettytable==3.10.0
    - kornia==0.7.2
    - transformers==4.36.2
    - torchmetrics==1.3.1
    - pandas==2.0.3